# Generated by Django 3.2 on 2021-08-15 13:04

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=mainapp.models.recipe_image_file_path),
        ),
    ]
